baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"
title = "ZOZO MOD"                     # site title
theme = "ZozoMod"
hasCJKLanguage = true                  # has chinese/japanese/korean characters
summaryLength = 100
paginate = 4                           # number of articles displayed on index page
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                              #essential                     
  name = "John Doe"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config nav
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "the site subtitle"
  footerSlogan = "My spiritual home"
  keywords = ["Hugo","theme","ZozoMod"]
  description = "Hugo theme ZozoMod example site."
  enableMathJax = false
  enableKaTeX = true
  enableSummary = true
  mainSections = ["posts","post"]
  
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:title/"

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = " "
  twitter = " "
  facebook = " "
  instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
